jobs:
  workflow:
    name: Run
    runs-on: ubuntu-20.04

    steps:
      - name: Initialize
        uses: actions/checkout@v2
      - name: Get Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Check
        run: ./test/workflow

name: Run

on:
  schedule:
    - cron: "50 */6 * * *"
